### ISSUE TITLE
Documentation fails to generate

### ISSUE THREAD

**Issue by z64** [imdrasil/jennifer.cr#12]
Hi! First of all, thanks for the amazing effort put into this!

I went to build the docs for this project (`v0.3.1` and `master`) and it could not compile:
```
➜  jennifer.cr git:(master) cr docs
Error in line 1: while requiring "./src/**"

in src/jennifer.cr:12: while requiring "./jennifer/query_builder/*"

require "./jennifer/query_builder/*"
^

in src/jennifer/query_builder/condition.cr:1: while requiring "./criteria"

require "./criteria"
^

in src/jennifer/query_builder/criteria.cr:4: undefined constant DBAny

      alias Rightable = Criteria | DBAny | Array(DBAny)
```
While the README is excellent, the terse and familiar searchable docs would be great to have.

I find time to look into fixing this, I'll open a PR.

---
Side note - is the TODO list README entirely up to date? It mentions PG::Array support not being present, however there are `Array` types in the `DBAny` union here: https://github.com/imdrasil/jennifer.cr/blob/master/src/jennifer/adapter/postgres.cr#L8-L12

If you wouldn't mind going in to more detail on the current support for this, that would be great - I do plan to make use of a `PG::Array` column in my app.

**Comment by imdrasil** [comment]
About documentation - till now docs generation was not major feature. But I agree - it really could help to go through some parts. So will take a look

About arrays for pg - yes, they officially are not supported because there is no test to cover usage of them, but their definition are added to `DBAny` union. Right when I be sure them work correctly - will add   to documentation. The same history with `sqlite3` support - work is started but a lot of functionality are not finished (and part of them is impossible to implement because of it's restrictions)

**Comment by z64** [comment]
Good to hear. Thanks for the timely reply!

**Comment by imdrasil** [comment]
I'll put array support as next feature on the roadmap. Next will be model mapping [auto generation](https://github.com/imdrasil/jennifer.cr/issues/11])

**Comment by imdrasil** [comment]
now I think we could close this one

**Comment by z64** [comment]
Docs works, I'll get to arrays when I need them in my app.

Thanks so much!!
