### ISSUE TITLE
ON CONFLICT support?

### ISSUE THREAD

**Issue by taylorfinnell** [imdrasil/jennifer.cr#139]
Is adding support for `INSERT ... ON CONFICT ...` something being considered? I can maybe take a stab at it at some point if it's a wanted feature

**Comment by imdrasil** [comment]
@taylorfinnell it is very interesting. Regarding mysql, it has slightly different construction `ON DUPLICATE KEY` which will complicate providing similar (or at least not very different) interface for postgre and mysql. We should discuss how this should be implemented.

**Comment by taylorfinnell** [comment]
How do you think the api should look? Should it be options to #save (possible issues with determining if it is a new record?). Or some other new method like #upsert

**Comment by imdrasil** [comment]
sorry for such long response - had (and still have -_-) a lot of work. As a starting point may be next points that should be taken into account:
- new functionality should be realized for `Jennifer::QueryBuilder::Query` (for generic purposes - to be able to use it without using models) and for `Jennifer::QueryBuilder::ModelQuery`
- all sql related stuff should be placed in the corresponding sql generator class
- the api method name may be `upsert` - adding extra method (instead of patching existent one) simplify maintainability of code and increase the flexibility of each method; as an argument, we should specify should we ignore cases with duplications or use update (I know that postgres provides more flexible configuratin options, but lets start with simple generic solution)

These are my first thoughts. What do you think about this?

**Comment by imdrasil** [comment]
This feature will be added to `0.8.0` release branch in the 2 weeks or so.

**Comment by imdrasil** [comment]
`release/0.8.0` has got upsert functionality for `mysql` and `postgres` adapters. SQLite adapter will get this after release. If you need any adjustment, face any issue or have any proposal - feel free to open new issue.
