### ISSUE TITLE
Can not edit Model which is a relational Model

### ISSUE THREAD

**Issue by Prutheus** [imdrasil/jennifer.cr#175]
I have my model user:

```
class User < Jennifer::Model::Base
  with_timestamps
  mapping(
    id: Primary32,
    email: String,
    password: String,
    ip: String,
    token: String?,
    created_at: Time?,
    updated_at: Time?
  )

  has_many :searches, Search
end
```

and my model search:

```
class Search < Jennifer::Model::Base
  with_timestamps
  mapping(
    id: Primary32,
    user_id: Int32,
    active: Bool,
    interval: Int32,
    running: Bool,
    next_run: Time,
    name: String,
    platform: String,
    options: JSON::Any,
    created_at: Time?,
    updated_at: Time?
  )
  JSON.mapping(
    id: Int32 | Nil,
    user_id: Int32,
    active: Bool,
    interval: Int32,
    running: Bool,
    next_run: Time,
    name: String,
    platform: String,
    options: JSON::Any,
    created_at: Time?,
    updated_at: Time?
  )

  belongs_to :user, User
  has_many :results, Result
end
```

when i do following: 

```
    search = Search.where {_id == id}.first
    if search
      if search.active
        search.active = false
      else
        search.active = true
        search.next_run = Time.now
      end
      pp search.save
      raise Exception.new({status: "200 OK"}.to_json)
    else
      raise Exception.new({status: "404 Not Found"}.to_json)
    end
```

`pp search.save` results in false ... why? I can't edit the search ... I have no clue why...

**Comment by z64** [comment]
Just a cursory glance at the source, I have a pretty good guess I think.

Jennifer's `mapping` macro defines [custom setters](https://github.com/imdrasil/jennifer.cr/blob/master/src/jennifer/model/mapping.cr#L21-L28) which set internal flags, so that the proper query can be built when you call `.save`.

When you execute the `JSON.mapping` macro, these setters are *overwritten* by a [basic setter](https://github.com/imdrasil/jennifer.cr/blob/master/src/jennifer/model/mapping.cr#L21-L28) that only updates the ivar, and not Jennifer's internal flags (`@{{key.id}}_changed`).

The solution should just be to use `JSON.mapping` *first*, so that Jennifer's `mapping` setters are defined last.

```cr
class Search < Jennifer::Model::Base
  JSON.mapping(...)

  mapping(...)
end
```

Hope this helps!

**Comment by Prutheus** [comment]
Thanks.

**Comment by z64** [comment]
You're welcome! I assume that worked for you then?

I think it is impossible for the library to catch this kind of mistake - it can be an easy one to make unfortunately 🙁 

The best thing to do against this issue would be to update the [model mapping guide](https://github.com/imdrasil/jennifer.cr/blob/master/docs/model_mapping.md) with a note recommending that users be careful to use Jennifer's `mapping` last if using something like `JSON.mapping` or the new `JSON::Serializable` model. I think it is probably pretty common enough for DB models to also be JSON-mapped for serving APIs.

What do you think @imdrasil ?

**Comment by z64** [comment]
I've sent #176 to document this if that sounds okay 🙂
