### ISSUE TITLE
support numeric => Float64 in postgresql

### ISSUE THREAD

**Issue by huuhait** [imdrasil/jennifer.cr#357]
Hi i've some trouble in postgres adapter

if i use type numeric for some column so i cant validate it with method `greater_than` and other method
![image](https://user-images.githubusercontent.com/40519768/104161500-8b265380-5425-11eb-8e74-af1d7588befa.png)

**Comment by huuhait** [comment]
if i use Float64 for this column
![image](https://user-images.githubusercontent.com/40519768/104173634-a9e21580-5438-11eb-939f-11c97a4d87c7.png)

**Comment by imdrasil** [comment]
Currently the only convenient option for this case is converter from `PG::Numeric` to `Float64` [`Jennifer::Model::NumericToFloat64Converter`](https://github.com/imdrasil/jennifer.cr/blob/master/src/jennifer/adapter/postgres/model/numeric_to_float64_converter.cr). For general information about converters check this [section](https://github.com/imdrasil/jennifer.cr/blob/f3d53a12d18d448c2e08f47b4c5530a09342327e/docs/model_mapping.md#converters).

P.S. This issue is in my radar - going to add more reliable alternative for high precision calculations

**Comment by imdrasil** [comment]
Now you also can use `Jennifer::Model::BigDecimalConverter` to convert `Pg::Numeric` to `BigDecimal`
