### ISSUE TITLE
JSON columns with array values being updated is not recognized as "changed" & does not save

### ISSUE THREAD

**Issue by crimson-knight** [imdrasil/jennifer.cr#418]
Using Postgres and a model with a JSONB column with type `JSON::Any` that has an array value that changes is not considered "changed" and does not save the record.

I made an example app here: https://github.com/crimson-knight/jennifer-json-test

Basically if I have a model `Example` with a JSON attribute value of
```json
{
  "test": [ "first_value" ]
}
```

and I update it to 
```json
{
  "test": [ "first_value", "second_value" ]
}
```

Saving the record does not actually save and checking with `changed?` shows that Jennifer believes the model has not changed.

However, when the array is empty and then a new value is added to the array then the record will save. So this bug only appears after the first value of the array has been added.

**Comment by crimson-knight** [comment]
I want to clarify this affects the `#save` and `#set_attribute` methods, but using `#update_column` works as expected

**Comment by imdrasil** [comment]
This is a common issue with a json objects. The trick here is that `new_json_array_value` is actually an instance of array from `random_example.random`. That's why when you change it you change the original object. Later on when you dump json to a string and parse it back it doesn't help as `random_example` already has a similar json. To avoid such issues you have 2 options:
- create a deep clone of an object you want to modify and then assign it back
- call `random_example.random_will_change!` to mark the attribute as changed

**Comment by crimson-knight** [comment]
Using `#{attribute}_will_change!` method made it work, thank you!
