### ISSUE TITLE
Allow multiple configurations

### ISSUE THREAD

**Issue by sgargan** [imdrasil/jennifer.cr#58]
Config is currently stored in a number of class level variables and means that you can only be connected to one database in any app. It would be very useful to be able to have multiple configurations and use these on a per model basis. 

First pass at this would be to 
 - [ ] encapsulate the configuration in an object
 - [ ] a simple registry for creating and storing configs.
 - [ ] modifications to Model & migration bases to allow specification of a config

Second pass, (possibly as a separate issue)  would be to allow runtime selection and configuration of adapters instead of compile time. Happy to make these changes if you're :+1:

**Comment by imdrasil** [comment]
Adding multiple configuration isn't hard - I have an idea how it will look. But situation with multiple adapters (both mysql and postgre) is not so optimistic. Postgres has much more functionality - that's why at the very beginnig I decided to fully separate them. Multiple adapters issue is really important - (I know), but for now it has not high priority.

**Comment by imdrasil** [comment]
Thanks for your help ).

Let allow to specify several config instances and realize next API:
```crystal
Jennifer::Config.configure do |conf|
  # here will be default settings
end

Jennifer::Config.configure("custom_db") do |conf|
  # here is for custom custom_db
end

Jennifer::Config.configure # returns default configs
Jennifer::Config.configure("custom_db") # I think you've got my point ;-)

class MyModel < Jennifer::Model::Base
  set_adapter "custom_db" # switching to new configs
end

class Migration3123123 < Jennifer::Migration::Base
  set_adapter "custom_db"
end
```

I propose to use `set_adapter` because per each configuration will be created separated adapter instance. That's why such behavior should be supported by `Jennifer::Adapter` as well.

Also configuration yaml file should support loading such configs

Feel free to make any questions here or directly to my email (if y will get such need).

**Comment by imdrasil** [comment]
@sgargan do u need any help from my side?

**Comment by sgargan** [comment]
The static config is pretty entrenched, I've got most of it replaced and
selectable as suggested, just have a few stubborn tests to get working
again. Hopefully have a PR out to discuss soon.

One thing it would be good for you to be thinking about in the meantime is
how you'd like to support multiple adapters as this work will lead into
that. There are a couple of places where adapter specific functionality is
compiled in and expected to be available statically that will need to break
(table creation in migrations is one that springs to mind). There are a
couple of ways to approach this and it would be good to get your opinion on
which you prefer.

**Comment by imdrasil** [comment]
The easiest way - to allow only one adapter type (mysql or postgres) but such approach is not very useful (.  Another option - inherit all classes which should be customized and override methods. Also in such case `DBAny` will be used from postgres adapter because I guess there is no other way to maintain all possible arguments.
It seems I have to start work on implementing multiple adapter support :crying_cat_face:
